validation

diff --git a/.github/workflows/unity-xref-maps.yml b/.github/workflows/unity-xref-maps.yml
--- a/.github/workflows/unity-xref-maps.yml
+++ b/.github/workflows/unity-xref-maps.yml
@@ -49,7 +49,19 @@ jobs:
           dotnet-version: 8.x
       - run: |
           dotnet tool install -g docfx
-          mkdir -p ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }}
+
+          # test unity projects path
+          if [ ! -d ${{ github.workspace }}/UnityCsReference/Projects/CSharp ]; then
+            echo "Unity project path not found"
+            exit 1
+          fi
+
+          # validate .csproj files in Unity project path
+          if [ ! "$(ls -A ${{ github.workspace }}/UnityCsReference/Projects/CSharp)" ]; then
+            echo "No .csproj files found in Unity project path"
+            exit 1
+          fi
+
           # for versions between 2019.1 and 2021.3 (inclusive) add Debug configuration property
           if [[ ${{ matrix.unity_version }} == 2019.* || ${{ matrix.unity_version }} == 2020.* || ${{ matrix.unity_version }} == 2021.* ]]; then
             docfx metadata ${{ github.workspace }}/.docfx/docfx.json --output ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} --logLevel verbose --property Configuration=Debug
