add additional checks

diff --git a/.github/workflows/unity-xref-maps.yml b/.github/workflows/unity-xref-maps.yml
--- a/.github/workflows/unity-xref-maps.yml
+++ b/.github/workflows/unity-xref-maps.yml
@@ -44,12 +44,23 @@ jobs:
           dotnet-version: 8.x
       - run: |
           dotnet tool install -g docfx
-          echo ${{ matrix.unity_version }}
           # for versions between 2019.1 and 2021.3 (inclusive) add Debug configuration property
           if [[ ${{ matrix.unity_version }} == 2019.* || ${{ matrix.unity_version }} == 2020.* || ${{ matrix.unity_version }} == 2021.* ]]; then
             docfx metadata ${{ github.workspace }}/.docfx/docfx.json --output ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} --logLevel error --property Configuration=Debug
           else
             docfx metadata ${{ github.workspace }}/.docfx/docfx.json --output ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} --logLevel error
+          fi
+
+          # check if metadata generation was successful
+          if [ $? -ne 0 ]; then
+            echo "Failed to generate metadata for Unity version ${{ matrix.unity_version }}"
+            exit 1
+          fi
+
+          # check if xref directory is not empty
+          if [ ! "$(ls -A ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }})" ]; then
+            echo "No metadata found for Unity version ${{ matrix.unity_version }}"
+            exit 1
           fi
 
           chmod +x ${{ github.workspace }}/generate-xref-map.sh
