try a different strategy

diff --git a/.github/workflows/unity-xref-maps.yml b/.github/workflows/unity-xref-maps.yml
--- a/.github/workflows/unity-xref-maps.yml
+++ b/.github/workflows/unity-xref-maps.yml
@@ -33,7 +33,7 @@ jobs:
   # genearte docfx metadata for each unity version
   generate_metadata:
     needs: get_unity_versions
-    runs-on: ubuntu-latest
+    runs-on: windiws-latest
     strategy:
       fail-fast: false
       matrix:
@@ -45,68 +45,46 @@ jobs:
           repository: Unity-Technologies/UnityCsReference
           path: UnityCsReference
           ref: ${{ matrix.unity_version }}
-      - run: |
-          echo "::group::Directory structure for Unity version ${{ matrix.unity_version }}"
-          find UnityCsReference
-          echo "::endgroup::"
       - uses: actions/setup-dotnet@v4
         with:
           dotnet-version: 8.x
       - run: |
           echo "::group::DocFX metadata ${{ matrix.unity_version }}"
 
-          # for versions 2017 though 2021, install docfx version 2.61.0 else do latest
-          if [[ ${{ matrix.unity_version }} == 2017.* || ${{ matrix.unity_version }} == 2018.* || ${{ matrix.unity_version }} == 2019.* || ${{ matrix.unity_version }} == 2020.* || ${{ matrix.unity_version }} == 2021.* ]]; then
-            dotnet tool install -g docfx --version 2.61.0
-            dotnet tool restore
-          else
-            dotnet tool install -g docfx
-          fi
+          dotnet tool install -g docfx
 
           # for versions between 2019.1 and 2021.3 (inclusive) add Debug configuration property
-          if [[ ${{ matrix.unity_version }} == 2019.* || ${{ matrix.unity_version }} == 2020.* || ${{ matrix.unity_version }} == 2021.* ]]; then
+          if (${{ matrix.unity_version }} -like '2019.*' -or ${{ matrix.unity_version }} -like '2020.*' -or ${{ matrix.unity_version }} -like '2021.*') {
             docfx metadata ${{ github.workspace }}/.docfx/docfx.json --output ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} --logLevel diagnostic --property Configuration=Debug
-          else
+          }
+          else {
             docfx metadata ${{ github.workspace }}/.docfx/docfx.json --output ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} --logLevel diagnostic
-          fi
+          }
 
           # check if metadata generation was successful
-          if [ $? -ne 0 ]; then
-            echo "Failed to generate metadata for Unity version ${{ matrix.unity_version }}"
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Failed to generate metadata for Unity version ${{ matrix.unity_version }}"
             exit 1
-          fi
+          }
 
-          # check if directoy exists
-          if [ ! -d ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} ]; then
-            echo "No xref directory found for Unity version ${{ matrix.unity_version }}"
+          # check if directory exists
+          if (-Not (Test-Path -Path ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} -PathType Container)) {
+            Write-Error "No xref directory found for Unity version ${{ matrix.unity_version }}"
             exit 1
-          fi
+          }
 
           # check if xref directory is not empty
-          if [ ! "$(ls -A ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }})" ]; then
-            echo "No metadata found for Unity version ${{ matrix.unity_version }}"
+          if (-Not (Get-ChildItem -Path ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }})) {
+            Write-Error "No metadata found for Unity version ${{ matrix.unity_version }}"
             exit 1
-          fi
+          }
 
           echo "::endgroup::"
-          chmod +x ${{ github.workspace }}/generate-xref-map.sh
-          echo "::group::Generate xref map for Unity version ${{ matrix.unity_version }}"
-          ${{ github.workspace }}/generate-xref-map.sh ${{ matrix.unity_version }} ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} ${{ github.workspace }}/_site
-
-          # Ensure generation script succeeded
-          if [ $? -ne 0 ]; then
-            echo "Failed to generate xref map for Unity version ${{ matrix.unity_version }}"
-            exit 1
-          fi
-
-          echo "::endgroup::"
-
           # Additional logging
           echo "::group::Directory contents after generation"
-          ls -R ${{ github.workspace }}/.docfx/xref/
-          ls -R ${{ github.workspace }}/_site/
+          Get-ChildItem -Recurse ${{ github.workspace }}/.docfx/xref/
           echo "::endgroup::"
-        shell: bash
+        shell: pwsh
         name: Generate Xref Metadata
       - uses: actions/upload-artifact@v4
         if: always()
@@ -120,6 +98,27 @@ jobs:
           retention-days: 1
           name: ${{ matrix.unity_version }}-metadata
           path: ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }}/
+  process_metadata:
+    needs: [generate_metadata, get_unity_versions]
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        unity_version: ${{ fromJson(needs.get_unity_versions.outputs.UNITY_VERSIONS) }}
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/download-artifact@v4
+        with:
+          name: xref-${{ matrix.unity_version }}
+      - run: |
+          chmod +x ${{ github.workspace }}/generate-xref-map.sh
+          echo "::group::Generate xref map for Unity version ${{ matrix.unity_version }}"
+          ${{ github.workspace }}/generate-xref-map.sh ${{ matrix.unity_version }} ${{ github.workspace }}/.docfx/xref/${{ matrix.unity_version }} ${{ github.workspace }}/_site
+          # Ensure generation script succeeded
+          if [ $? -ne 0 ]; then
+            echo "Failed to generate xref map for Unity version ${{ matrix.unity_version }}"
+            exit 1
+          fi
+          echo "::endgroup::"
   # get the xref maps from the artifacts and publish them to gh-pages
   publish_xref_maps:
     needs: generate_metadata
